### ISSUE TITLE
Crash related to toro entity from toroquest

### ISSUE THREAD

**Issue by Hellcommander** [ToroCraft/ToroQuest#116]
here is the crash might be related to it defending itself:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.11.2-5.0.0.jar)
  literalascension (literalascension-1.11.2-1.0.1.0.jar)
  ForgelinPlugin (Forgelin-1.2.0.jar)
  LoadingPlugin (Quark-r1.2-77.jar)
  offlineskins (OfflineSkins-1.11.2-v1.jar)
  TANLoadingPlugin (ToughAsNails-1.11-2.0.4.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  ServerPropertiesLAN (ServerPropertiesLAN-2.4.jar)
  IvToolkit (IvToolkit-1.3.2.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  llibrary (llibrary-1.7.4-1.11.2.jar)
  MMFMLCorePlugin (MultiMine-1.11.2.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.2.5.0.jar)
  LoadingPlugin (HardcoreDarkness-MC1.11-1.8.1.jar)
  DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  LoadingPlugin (CrystalMod-1.11.2-4.1.0dev.jar)
  SHLoadingPlugin (ScalingHealth-1.11-1.0.3-36.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2/2/17 3:40 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:19)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:95)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:892)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2255)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:680)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)
	at net.minecraft.world.World.func_72939_s(World.java:1747)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:19)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:95)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:892)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2255)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:680)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)

-- Entity being ticked --
Details:
	Entity Type: toroquest:toro (net.torocraft.toroquest.entities.EntityToro)
	Entity ID: 19801
	Entity Name: Toro
	Entity's Exact location: -3601.42, 71.00, -6635.47
	Entity's Block location: World: (-3602,71,-6636), Chunk: (at 14,4,4 in -226,-415; contains blocks -3616,0,-6640 to -3601,255,-6625), Region: (-8,-13; contains chunks -256,-416 to -225,-385, blocks -4096,0,-6656 to -3585,255,-6145)
	Entity's Momentum: -0.17, -0.08, 0.11
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1747)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: BOP World 14
	All players: 1 total; [EntityPlayerMP['Arendeth'/821, l='BOP World 14', x=-3543.69, y=71.00, z=-6597.99]]
	Chunk stats: ServerChunkCache: 774 Drop: 0
	Level seed: 3642846303007749886
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"continents","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.1070423,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateNetherPlants":true,"generateEndFeatures":true,"mainNoiseScaleX":212.22534,"mainNoiseScaleY":106.61267,"mainNoiseScaleZ":177.02113,"coordinateScale":212.2324,"heightScale":85.49296,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (-48,66,-64), Chunk: (at 0,4,0 in -3,-4; contains blocks -48,0,-64 to -33,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 36103 game time, 41673 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 40706 (now: false), thunder time: 21597 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 23306704960 bytes (22227 MB) / 27702591488 bytes (26419 MB) up to 27702591488 bytes (26419 MB)
	JVM Flags: 36 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx26G -Xms26G -Xmn2G -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:-UseAdaptiveSizePolicy -XX:+UseStringCache -XX:+OptimizeStringConcat -XX:+UseThreadPriorities -XX:-UseParallelGC -XX:+UseTLAB -XX:+CMSIncrementalMode -XX:UseSSE=4 -XX:+UseLargePages -XX:+AlwaysPreTouch
	IntCache: cache: 16, tcache: 0, allocated: 22, tallocated: 21
	FML: MCP 9.38 Powered by Forge 13.20.0.2226 Optifine OptiFine_1.11.2_HD_U_B6 210 mods loaded, 210 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2226.jar) 
	UCHIJAAAA	forge{13.20.0.2226} [Minecraft Forge] (forge-1.11.2-13.20.0.2226.jar) 
	UCHIJAAAA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJAAAA	ivtoolkit{1.3.2} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	serverpropertieslan{2.4} [Server Properties LAN] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.1.7} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.7.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	rpghud{3.2} [RPG-Hud] ([1.11] RPG-HUD 3.2.jar) 
	UCHIJAAAA	movillages{1.5.3} [Mo' Villages] ([1.11]MoVillages-1.5.3.jar) 
	UCHIJAAAA	bettercombatmod{1.4.0} [Better Combat] ([MC 1.11.X] BetterCombatMod 1.4.jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] ([MC 1.11.X] BetterCombatMod 1.4.jar) 
	UCHIJAAAA	jei{4.2.4.227} [Just Enough Items] (jei_1.11.2-4.2.4.227.jar) 
	UCHIJAAAA	abyssalcraft{1.9.3.10} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.3.10.jar) 
	UCHIJAAAA	achunkloader{1.11-1.2.0} [A Chunk Loader] (achunkloader-1.11.2-1.2.0.jar) 
	UCHIJAAAA	forgeendertech{2.0.2.0} [Forge Endertech] (ForgeEndertech-1.11.2-2.0.2.0.jar) 
	UCHIJAAAA	adhooks{1.11.2-2.0.1.1} [Advanced Hook Launchers] (AdHooks-1.11.2-2.0.1.1.jar) 
	UCHIJAAAA	advancedsticks{1.4.3} [§9Advanced Sticks Mod] (Advanced Sticks 1.11.2 by XxRexRaptorxX (v.1.4.3).jar) 
	UCHIJAAAA	advancedcombat{1.0.1} [Advanced Combat] (advancedcombat-1.0.1-[1.11.2].jar) 
	UCHIJAAAA	animalbikes{1.11.2} [Animal Bikes] (AnimalBikes_1.11.2(24jan17).jar) 
	UCHIJAAAA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJAAAA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJAAAA	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJAAAA	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJAAAA	as_extraresources{0.1.1} [§9AS: §6Extra Resources Add-on] (AS-ExtraResources 1.11.2 by XxRexRaptorxX (v.0.1.1).jar) 
	UCHIJAAAA	psi{r1.1-46} [Psi] (Psi-r1.1-46.jar) 
	UCHIJAAAA	quark{r1.2-77} [Quark] (Quark-r1.2-77.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	barkifier{1.1} [Barkifier] (Barkifier MC1.11.2 v1.1.jar) 
	UCHIJAAAA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJAAAA	bdlib{1.13.1.4} [BD Lib] (bdlib-1.13.1.4-mc1.11.2.jar) 
	UCHIJAAAA	betterachievements{0.4.1.44} [Better Achievements] (BetterAchievements-1.11.2-0.4.1.44.jar) 
	UCHIJAAAA	bettersprinting{1.1.9} [Better Sprinting] (BetterSprinting  MC-1.11.2  v1.1.9.jar) 
	UCHIJAAAA	biomesoplenty{6.0.1.2145} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.1.2145-universal.jar) 
	UCHIJAAAA	blockdispenser{1.0} [BlockDispenser] (BlockDispenser-1.1-2.jar) 
	UCHIJAAAA	cavern{1.6.2} [Cavern] (Cavern_1.11-v1.6.2.jar) 
	UCHIJAAAA	ceanimals{1.3.0} [Crop-Eating Animals] (ceanimals-1.11.2-1.3.0.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJAAAA	chalice{1.11.2-2.6} [Chalice] (chalice-1.11.2-2.6.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	chancecubes{1.11-2.3.3.136} [Chance Cubes] (ChanceCubes-1.11-2.3.3.136.jar) 
	UCHIJAAAA	chiselsandbits{13.9} [Chisels & Bits] (chiselsandbits-13.9.jar) 
	UCHIJAAAA	clienttweaks{2.1.2} [Client Tweaks] (ClientTweaks_1.11-2.1.2.jar) 
	UCHIJAAAA	cyclopscore{0.9.2} [Cyclops Core] (CyclopsCore-1.11.2-0.9.2.jar) 
	UCHIJAAAA	commoncapabilities{1.3.1} [CommonCapabilities] (CommonCapabilities-1.11.2-1.3.1.jar) 
	UCHIJAAAA	convenientadditions{1.0.17-27} [Convenient Additions] (ConvenientAdditions-1.0.17-build27.jar) 
	UCHIJAAAA	crystalmod{4.1.0dev} [Crystal Mod] (CrystalMod-1.11.2-4.1.0dev.jar) 
	UCHIJAAAA	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2_beta(22jan17).jar) 
	UCHIJAAAA	cxlibrary{1.4.0} [CXLibrary] (cxlibrary-1.11.2-1.4.0.jar) 
	UCHIJAAAA	cyclicmagic{1.0.0} [Cyclic] (Cyclic-1.11.2-1.0.0.jar) 
	UCHIJAAAA	dailies{1.11.2-7} [Bailey's Dailies] (dailies-1.11.2-7.jar) 
	UCHIJAAAA	ding{1.0.1} [Ding] (Ding-1.11-1.0.1.jar) 
	UCHIJAAAA	durabilityshow{4.1.0} [Durability Show] (Durability Show-1.11.2-4.1.0.jar) 
	UCHIJAAAA	dynamiclights{1.4.6} [Dynamic Lights] (DynamicLights-1.11.2.jar) 
	UCHIJAAAA	dynamiclights_onfire{1.0.7} [Dynamic Lights on burning] (DynamicLights-1.11.2.jar) 
	UCHIJAAAA	dynamiclights_creepers{1.0.6} [Dynamic Lights on Creepers] (DynamicLights-1.11.2.jar) 
	UCHIJAAAA	dynamiclights_dropitems{1.1.0} [Dynamic Lights on ItemEntities] (DynamicLights-1.11.2.jar) 
	UCHIJAAAA	dynamiclights_entityclasses{1.0.1} [Dynamic Lights on specified Entities] (DynamicLights-1.11.2.jar) 
	UCHIJAAAA	dynamiclights_mobequipment{1.1.0} [Dynamic Lights on Mob Equipment] (DynamicLights-1.11.2.jar) 
	UCHIJAAAA	dynamiclights_flamearrows{1.0.1} [Dynamic Lights on Flame enchanted Arrows] (DynamicLights-1.11.2.jar) 
	UCHIJAAAA	dynamiclights_floodlights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.11.2.jar) 
	UCHIJAAAA	dynamiclights_otherplayers{1.0.9} [Dynamic Lights Other Player Light] (DynamicLights-1.11.2.jar) 
	UCHIJAAAA	dynamiclights_theplayer{1.1.3} [Dynamic Lights Player Light] (DynamicLights-1.11.2.jar) 
	UCHIJAAAA	dsurround{3.2.5.0} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.2.5.0.jar) 
	UCHIJAAAA	earthworks{1.0.2} [Earthworks] (Earthworks-1.11.2-1.0.2.jar) 
	UCHIJAAAA	ea{v2.5.0a-mc1.10.2} [Ebon Arts] (EbonArts-v2.5.0a-mc1.11.0.jar) 
	UCHIJAAAA	forestry{5.3.0.31} [Forestry] (forestry_1.11.2-5.3.0.31.jar) 
	UCHIJAAAA	eleccore{1.6.381} [ElecCore] (ElecCore-1.11-1.6.381.jar) 
	UCHIJAAAA	eggs{1.0} [Eat the Eggs!] (EM3R50N-EatTheEggs-1.11.2-13.20.0.2201.jar) 
	UCHIJAAAA	logicaldrops{0.9.4} [Logical Drops] (EM3R50N-LogicalDrops-1.11.2-13.20.0.2201.jar) 
	UCHIJAAAA	endercompass{1.2.5.1} [Ender Compass] (EnderCompass-1.11-1.2.5.1.jar) 
	UCHIJAAAA	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCHIJAAAA	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCHIJAAAA	epicsiegemod{12.0.153} [Epic Siege Mod] (EpicSiegeMod-12.0.153.jar) 
	UCHIJAAAA	etlunar{1.11.2-0.11.0b} [ET Lunar] (etlunar-1.11.2-0.11.0b.jar) 
	UCHIJAAAA	extrabitmanipulation{1.11.2-3.0.4} [Extra Bit Manipulation] (ExtraBitManipulation-1.11.2-3.0.4.jar) 
	UCHIJAAAA	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11-3.7.4.jar) 
	UCHIJAAAA	extrarails{1.2.1} [Extra Rails] (ExtraRails-1.11-1.2.1.jar) 
	UCHIJAAAA	fairylights{2.0.6} [Fairy Lights] (fairylights-2.0.6-1.11.jar) 
	UCHIJAAAA	floricraft{1.1.4} [Floricraft] (Floricraft-1.11.2-1.1.4.jar) 
	UCHIJAAAA	fluidconverters{2.1.1} [FluidConverters] (FluidConverters-1.11.2-2.1.1.jar) 
	UCHIJAAAA	friendlyfire{1.4.0} [Friendly Fire] (FriendlyFire-1.11-1.4.0.jar) 
	UCHIJAAAA	funnels{1.2.1} [Funnels] (Funnels-1.11-1.2.1.jar) 
	UCHIJAAAA	gendustry{1.6.5.4} [GenDustry] (gendustry-1.6.5.4-mc1.11.2.jar) 
	UCHIJAAAA	pressure{1.3.1.4} [Pressure Pipes] (pressure-1.3.1.4-mc1.11.2.jar) 
	UCHIJAAAA	advgenerators{0.9.20.2} [Advanced Generators] (generators-0.9.20.2-mc1.11.2.jar) 
	UCHIJAAAA	geographicraft{0.8.7} [GeographiCraft] (GeographiCraft-0.8.7.jar) 
	UCHIJAAAA	giacomosfoundry{1.3.10} [Giacomo's Foundry] (GiacomosFoundry-1.11.2-1.3.10.jar) 
	UCHIJAAAA	grapplemod{1.11-v9} [Grappling hook mod] (grapplemod-1.11-v9.jar) 
	UCHIJAAAA	grue{1.3.4} [Grue] (Grue-1.11.2-1.3.4.jar) 
	UCHIJAAAA	hardcoredarkness{1.8.1} [Hardcore Darkness] (HardcoreDarkness-MC1.11-1.8.1.jar) 
	UCHIJAAAA	hardcoreore{0.0.12} [Hardcore ORE] (HardcoreORE-1.11.2-0.0.12.jar) 
	UCHIJAAAA	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs-1.11.2.jar) 
	UCHIJAAAA	infinitefluids{1.1.0} [InfiniteFluids] (infinitefluids-1.11-1.1.0.jar) 
	UCHIJAAAA	intwheel{1.2.2} [Interaction Wheel] (intwheel-1.1x-1.2.2.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-75-f4ba194} [Inventory Tweaks] (InventoryTweaks-1.62-dev-75.jar) 
	UCHIJAAAA	itemeditor{1.11.x-0.1.0.0} [Item Editor GUI] (itemeditor-1.11.x-0.1.0.0.jar) 
	UCHIJAAAA	iv{2.0.2} [Improved Villagers] (iv-2.0.2.jar) 
	UCHIJAAAA	japta{1.11.7} [JAPTA] (JAPTA-1.11-1.11.7.jar) 
	UCHIJAAAA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.11.2.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHIJAAAA	justenoughbuttons{1.11.2-1.4.1} [Just Enough Buttons] (justenoughbuttons-1.11.2-1.4.1.jar) 
	UCHIJAAAA	justenoughdimensions{1.2.0} [Just Enough Dimensions] (justenoughdimensions-1.11.2-1.2.0.jar) 
	UCHIJAAAA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJAAAA	jet{2.1.41} [JustEnoughTooltips] (JustEnoughTooltips-1.11-2.1.41.jar) 
	UCHIJAAAA	kleeslabs{4.3.2} [KleeSlabs] (KleeSlabs_1.11.2-4.3.2.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.13.2-1.11.jar) 
	UCHIJAAAA	lightair{1.11-2.2} [LightAir] (lightair-1.11-2.2.jar) 
	UCHIJAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	UCHIJAAAA	literalascension{1.11.2-1.0.1.0} [Literal Ascension] (literalascension-1.11.2-1.0.1.0.jar) 
	UCHIJAAAA	lunatriuscore{1.1.2.39} [LunatriusCore] (LunatriusCore-1.11-1.1.2.39-universal.jar) 
	UCHIJAAAA	malisiscore{1.11.2-5.0.0} [MalisisCore] (malisiscore-1.11.2-5.0.0.jar) 
	UCHIJAAAA	malisisdoors{1.11.2-6.0.0} [MalisisDoors] (malisisdoors-1.11.2-6.0.0.jar) 
	UCHIJAAAA	mcflux{2.0.5} [Minecraft-Flux] (mcflux-2.0.5.jar) 
	UCHIJAAAA	memorybar{1.0.2} [Memory Bar] (memorybar-1.0.2.jar) 
	UCHIJAAAA	mercurius{1.0.1} [Mercurius] (Mercurius-1.11.2-1.0.2.jar) 
	UCHIJAAAA	minecolonies{1.11-0.6.2464} [MineColonies] (minecolonies-universal-1.11-0.6.2464.jar) 
	UCHIJAAAA	minemenu{1.5.0} [MineMenu] (MineMenu-1.11.2-1.5.0-universal.jar) 
	UCHIJAAAA	mobblocker{1.11.2-1.4.1} [Mob Blocker] (mobblocker-1.11.2-1.4.1.jar) 
	UCHIJAAAA	mobtotems{1.11.2-0.2.2} [Mob Totems] (mobtotems-1.11.2-0.2.2.jar) 
	UCHIJAAAA	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.11-1.9.20160723.0.jar) 
	UCHIJAAAA	moreplayermodels{1.11.0} [MorePlayerModels] (MorePlayerModels_1.11.2(26jan17).jar) 
	UCHIJAAAA	morevanillaarmor{0.9} [More Vanilla Armors] (MoreVanillaArmors(v 0.8.1)[1.11.2].jar) 
	UCHIJAAAA	mousetweaks{2.7.1} [Mouse Tweaks] (MouseTweaks-2.7.1-mc1.11.2.jar) 
	UCHIJAAAA	multihotbar{1.0} [Multi-Hotbar] (multihotbar-1.11.2-2.1-dev-6.jar) 
	UCHIJAAAA	multimine{1.5.6} [Multi Mine] (MultiMine-1.11.2.jar) 
	UCHIJAAAA	multipagechest{1.8.0} [Multi Page Chest] (MultiPageChest-1.11-1.8.0.jar) 
	UCHIJAAAA	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.2.jar) 
	UCHIJAAAA	multistorage{1.3.4} [Multi-Storage] (multistorage-1.11.0-1.3.4.jar) 
	UCHIJAAAA	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.11.2-1.3.0.jar) 
	UCHIJAAAA	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	UCHIJAAAA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCHIJAAAA	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCHIJAAAA	notes{1.1.0} [Notes] (Notes-1.11.2-1.1.0.jar) 
	UCHIJAAAA	offlineskins{1.11.2-v1} [OfflineSkins] (OfflineSkins-1.11.2-v1.jar) 
	UCHIJAAAA	fodc{1.10.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.10.0.jar) 
	UCHIJAAAA	oreexcavation{1.3.85} [OreExcavation] (OreExcavation-1.3.85.jar) 
	UCHIJAAAA	harvestcraft{1.11.2b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2b.jar) 
	UCHIJAAAA	pandorasbox{2.1.6.1} [Pandora's Box] (PandorasBox-2.1.6.1.jar) 
	UCHIJAAAA	parachutemod{1.6.2} [Parachute Mod] (parachutemod-ng-1.11.2-1.6.2-423.jar) 
	UCHIJAAAA	stellarapi{0.6.4.1.2} [Stellar API] (Stellar API-0.6.4.1.2.jar) 
	UCHIJAAAA	photoptics{0.6.1.1.1} [Photoptics] (Photoptics-0.6.1.1.1.jar) 
	UCHIJAAAA	pickblockplus{1.1.1} [Pick Block Plus] (PickBlockPlus-1.11-1.1.1.jar) 
	UCHIJAAAA	jp.crafterkina.pipes{1.1.0.12} [Pipes] (Pipes-1.11-1.1.0.12.jar) 
	UCHIJAAAA	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
	UCHIJAAAA	platforms{1.3.2} [Platforms] (platforms-1.11.0-1.3.2.jar) 
	UCHIJAAAA	progenitor{0.0.3+1.11} [Progenitor] (progenitor-0.0.3+1.11.jar) 
	UCHIJAAAA	randomtweaks{1.11.2-1.0.0.1} [RandomTweaks] (randomtweaks-1.11.2-1.0.0.1.jar) 
	UCHIJAAAA	realistictorches{2.1.0} [Realistic Torches] (RealisticTorches-1.11.2-2.1.0.jar) 
	UCHIJAAAA	reccomplex{1.2.8} [Recurrent Complex] (RecurrentComplex-1.2.8.jar) 
	UCHIJAAAA	redstoneremote{@VERSION@} [Redstone Remote] (RedstoneRemote-1.11-1.0.0.jar) 
	UCHIJAAAA	refinedstorage{1.3.5} [Refined Storage] (refinedstorage-1.3.5.jar) 
	UCHIJAAAA	xreliquary{1.11.2-1.3.3.635} [Reliquary] (Reliquary-1.11.2-1.3.3.635.jar) 
	UCHIJAAAA	reptilemod{3.6.2} [Reptile Mod] (reptilemod-1.11.2-3.6.2-64.jar) 
	UCHIJAAAA	rftools{5.82} [RFTools] (rftools-1.1x-5.82.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.4} [RFTools Control] (rftoolsctrl-1.1x-1.6.4.jar) 
	UCHIJAAAA	rftoolsdim{4.53} [RFTools Dimensions] (rftoolsdim-1.1x-4.53.jar) 
	UCHIJAAAA	roguelike{1.6.3} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.3.jar) 
	UCHIJAAAA	roots{0.009} [Roots 2] (roots-2-0.009.jar) 
	UCHIJAAAA	roughmobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.11.jar) 
	UCHIJAAAA	ruins{16.4} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCHIJAAAA	silentlib{1.2.0} [Silent Lib] (SilentLib-1.11-1.2.0-30.jar) 
	UCHIJAAAA	scalinghealth{1.0.3} [Scaling Health] (ScalingHealth-1.11-1.0.3-36.jar) 
	UCHIJAAAA	schematica{1.7.8.157} [Schematica] (Schematica-1.11-1.7.8.157-universal.jar) 
	UCHIJAAAA	sensorcraft{0.5.0} [sensorcraft] (sensorcraft-1.11-0.5.0.jar) 
	UCHIJAAAA	silentgems{2.2.8} [Silent's Gems] (SilentsGems-1.11-2.2.8-112.jar) 
	UCHIJAAAA	sgextraparts{1.2.4} [Silent's Gems: Extra Parts] (SGExtraParts-1.11-1.2.4-12.jar) 
	UCHIJAAAA	shulkerbox{1.1.0} [Shulkerbox] (ShulkerBox 1.1.0.jar) 
	UCHIJAAAA	simpledimensions{1.3} [Simple Dimensions] (SimpleDimensions-MC1.11-1.3.jar) 
	UCHIJAAAA	simpleenhancements{v0.7.1a by Dot_Silver} [§2Simple §aEnhancements §2Mod] (SimpleEnhancementsMod-v0.7.1a-MCV1.11.jar) 
	UCHIJAAAA	simplegenerators{1.11.2-0.11.0a} [Simple Generators] (simplegenerators-1.11.2-0.11.0a.jar) 
	UCHIJAAAA	simpleleather{1.11.2-1.0} [Simple Leather] (simpleleather-1.11.2-1.0.jar) 
	UCHIJAAAA	simpleoregen{1.11.2-0.4.7} [SimpleOreGen] (simpleoregen-1.11.2-0.4.7.jar) 
	UCHIJAAAA	simplyconveyors{2.1.0} [Simply Conveyors] (SimplyConveyors-2.1.2.jar) 
	UCHIJAAAA	simulatednights{1.11.2-1.1.2} [Simulated Nights] (simulatednights-1.11.2-1.1.2.jar) 
	UCHIJAAAA	flammpfeil.slashblade{mc1.11-r7} [SlashBlade] (SlashBlade-mc1.11-r7.jar) 
	UCHIJAAAA	sophisticatedwolves{3.6.4} [Sophisticated Wolves] (SophisticatedWolves-3.6.4.jar) 
	UCHIJAAAA	souls{2.0.0} [Souls] (Souls-1.11.2-2.0.0.jar) 
	UCHIJAAAA	spartanshields{1.1c} [Spartan Shields] (SpartanShields-1.11-1.1c.jar) 
	UCHIJAAAA	stackie{1.6.0.45} [Stackie] (Stackie-1.11-1.6.0.45-universal.jar) 
	UCHIJAAAA	stepup{4.0-mc1.11} [StepUp] (StepUp-4.0-mc1.11.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.1.0} [Storage Drawers] (StorageDrawers-1.11.2-4.1.0.jar) 
	UCHIJAAAA	summoningstructures{1.0} [Summoning Structures] (SummoningStructures-1.6.jar) 
	UCHIJAAAA	superblocks{3.0r01} [Super Blocks 'n Buckets] (superblocks-mc1.11-3.0r01.jar) 
	UCHIJAAAA	tesla{1.3.0.51} [TESLA] (Tesla-1.11-1.3.0.51.jar) 
	UCHIJAAAA	theoneprobe{1.4.1} [The One Probe] (theoneprobe-1.1x-1.4.1.jar) 
	UCHIJAAAA	supersoundmuffler{1.0.1.4} [Super Sound Muffler] (supersoundmuffler-1.11.2-1.0.1.4.jar) 
	UCHIJAAAA	switchbow{1.0} [Switch-Bow] (switchbow-1.0.jar) 
	UCHIJAAAA	teletoro{1.11.2-21} [TeleToro] (teletoro-1.11.2-21.jar) 
	UCHIJAAAA	teslafied{1.0.0} [Teslafied] (teslafied-1.11-1.1.0.jar) 
	UCHIJAAAA	beneath{1.2.0} [The Beneath] (The Beneath-1.11.2-1.2.0.jar) 
	UCHIJAAAA	thedragonlib{1.11.2-2.2.0} [TheDragonLib] (thedragonlib-1.11.2-2.2.0.jar) 
	UCHIJAAAA	thut_wearables{2.1.2} [Thut's Wearables] (thut_wearables-2.1.2.jar) 
	UCHIJAAAA	thutcore{4.3.2} [ThutCore] (thutcore-4.3.2.jar) 
	UCHIJAAAA	thut_bling{1.0.1} [Thut's Bling] (thut_bling-1.0.1.jar) 
	UCHIJAAAA	thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.jar) 
	UCHIJAAAA	timehud{7.1.0} [Time HUD] (TimeHUD-Forge-1.11.2-7.1.0.jar) 
	UCHIJAAAA	toolupgrades{1.0.0} [§9Tool-Upgrades Mod] (Tool-Upgrades Mod 1.11.2 (v.1.0.0).jar) 
	UCHIJAAAA	topaddons{1.11.2-0.9.2} [TOP Addons] (topaddons-1.11.2-0.9.2.jar) 
	UCHIJAAAA	toroquest{1.11.2-2} [ToroQuest] (toroquest-1.11.2-2.jar) 
	UCHIJAAAA	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.4.jar) 
	UCHIJAAAA	trashslot{7.4.1} [TrashSlot] (TrashSlot_1.11-7.4.1.jar) 
	UCHIJAAAA	ultimate_unicorn_mod{1.5.9} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.11-1.5.10.jar) 
	UCHIJAAAA	underwaterutilities{@VERSION@} [Underwater Utilities] (UnderwaterUtilities-1.11-1.2.1.jar) 
	UCHIJAAAA	unifieditems{1.4.6.133} [Unified Items] (UnifiedItems-1.11.2-1.4.6-133.jar) 
	UCHIJAAAA	usefulnullifiers{1.3.3} [Useful Nullifiers] (usefulnullifiers-1.3.3.jar) 
	UCHIJAAAA	vc{4.11.0} [ViesCraft] (ViesCraft-1.11.2-4.11.0.jar) 
	UCHIJAAAA	villagerinventory{1.0.1} [Villager Inventory Viewer] (VillagerInventory-1.11-1.0.1.jar) 
	UCHIJAAAA	visiblearmorslots{3.0} [Visible Armor Slots] (VisibleArmorSlots[1.11.2]-3.0.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.11.2-5.0.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
literalascension (literalascension-1.11.2-1.0.1.0.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
ForgelinPlugin (Forgelin-1.2.0.jar)
  
LoadingPlugin (Quark-r1.2-77.jar)
  vazkii.quark.base.asm.ClassTransformer
offlineskins (OfflineSkins-1.11.2-v1.jar)
  lain.mods.skins.asm.ASMTransformer
TANLoadingPlugin (ToughAsNails-1.11-2.0.4.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  invtweaks.forge.asm.ContainerTransformer
ServerPropertiesLAN (ServerPropertiesLAN-2.4.jar)
  JaideepSinghHeer.Minecraft.mod.SPLANtransformerPort
IvToolkit (IvToolkit-1.3.2.jar)
  
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  cubex2.cxlibrary.CoreModTransformer
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MMFMLCorePlugin (MultiMine-1.11.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  brad16840.common.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  shetiphian.core.asm.ClassTransformer
RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.2.5.0.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
LoadingPlugin (HardcoreDarkness-MC1.11-1.8.1.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
LoadingPlugin (CrystalMod-1.11.2-4.1.0dev.jar)
  alec_wam.CrystalMod.asm.ClassTransformer
SHLoadingPlugin (ScalingHealth-1.11-1.0.3-36.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	List of loaded APIs: 
		* AbyssalCraftAPI (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Biome (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Block (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Disruption (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Energy (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Entity (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Event (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Integration (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Internal (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Item (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Necronomicon (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Recipe (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Ritual (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.11-2.1.0.0.b64.jar
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.3.jar
		* BetterAchievements|API (0.4.1.44) from BetterAchievements-1.11.2-0.4.1.44.jar
		* cavern.api (1.6.0) from Cavern_1.11-v1.6.2.jar
		* cavern.api.event (1.6.0) from Cavern_1.11-v1.6.2.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.9.jar
		* CoFHAPI (1.8.9R1.2.0B1) from theoneprobe-1.1x-1.4.1.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from UnderwaterUtilities-1.11-1.2.1.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.5.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.11.2-1.3.1.jar
		* compatlayer (0.1.7) from compatlayer-1.11.2-0.1.7.jar
		* convinientadditions|API (1.0) from ConvenientAdditions-1.0.17-build27.jar
		* Core (0.1) from CustomNPCs_1.11.2_beta(22jan17).jar
		* Core|Blocks (0.1) from CustomNPCs_1.11.2_beta(22jan17).jar
		* Core|Constants (0.1) from CustomNPCs_1.11.2_beta(22jan17).jar
		* Core|Entities (0.1) from CustomNPCs_1.11.2_beta(22jan17).jar
		* Core|Entities|Data (0.1) from CustomNPCs_1.11.2_beta(22jan17).jar
		* Core|Entities|Data|Role (0.1) from CustomNPCs_1.11.2_beta(22jan17).jar
		* Core|Events (0.1) from CustomNPCs_1.11.2_beta(22jan17).jar
		* Core|Handlers (0.1) from CustomNPCs_1.11.2_beta(22jan17).jar
		* Core|Handlers|Data (0.1) from CustomNPCs_1.11.2_beta(22jan17).jar
		* CrystalModapi (1) from CrystalMod-1.11.2-4.1.0dev.jar
		* dsurroundAPI (1.0) from DynamicSurroundings-1.11.2-3.2.5.0.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.6.381.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.6.381.jar
		* environmentaltech-api (1.11.2-0.11.0d) from environmentaltech-1.11.2-0.11.0d.jar
		* EpicSiegeMod|API (1.0) from EpicSiegeMod-12.0.153.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.0.31.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.0.31.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.4-mc1.11.2.jar
		* jeresources|API (0.6.2.104) from JustEnoughResources-1.11.2-0.6.2.104.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* jp.crafterkina.pipes.api (1.0) from Pipes-1.11-1.1.0.12.jar
		* jp.crafterkina.pipes.api.pipe (1.0) from Pipes-1.11-1.1.0.12.jar
		* jp.crafterkina.pipes.api.render (1.0) from Pipes-1.11-1.1.0.12.jar
		* JustEnoughItemsAPI (4.11.0) from ConvenientAdditions-1.0.17-build27.jar
		* mcfluxAPI|assistant (2.0.5) from mcflux-2.0.5.jar
		* mcfluxAPI|ex (2.0.5) from mcflux-2.0.5.jar
		* mcfluxAPI|fe (2.0.5) from mcflux-2.0.5.jar
		* mcjtylib_ng (2.3.5) from mcjtylib-1.1x-2.3.5.jar
		* pressureAPI (1.3.1.4) from pressure-1.3.1.4-mc1.11.2.jar
		* PsiAPI (4) from Psi-r1.1-46.jar
		* SchematicaAPI (1.1) from Schematica-1.11-1.7.8.157-universal.jar
		* SchematicaAPI|Events (1.1) from Schematica-1.11-1.7.8.157-universal.jar
		* SensorCraftAPI (3) from sensorcraft-1.11-0.5.0.jar
		* SilentGemsAPI (2) from SilentsGems-1.11-2.2.8-112.jar
		* stellarapi|api (0.6.4.1.2) from Stellar API-0.6.4.1.2.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* thut|API (1.0.0) from thutcore-4.3.2.jar
		* valkyrielib.api (1.11.2-0.11.0b) from valkyrielib-1.11.2-0.11.0c.jar
		* WailaAPI (1.3) from ConvenientAdditions-1.0.17-build27.jar
	Profiler Position: N/A (disabled)
	Player Count: 1 / 10; [EntityPlayerMP['Arendeth'/821, l='BOP World 14', x=-3543.69, y=71.00, z=-6597.99]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B6
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13431 Compatibility Profile Context 16.150.0.0
	OpenGlRenderer: AMD Radeon R9 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by frodare** [comment]
Thanks for posting this crash report, I will see if I can fix it tonight.

**Comment by frodare** [comment]
I am not be able to reproduce this error or see what could be causing it.  It is most likely caused by another mod doing something with entity `DataParameter's` or `onEntityUpdate()`.  Does the mod still cause this crash when it is the only mod?  Are there certain steps you need to do to cause this crash?  Without more info there isn't much I can do :(

**Comment by kreezxil** [comment]
I think this is related we punched a bull (el toro) in the head and our server crashed, this is that crash report: https://paste.fedoraproject.org/545136/16252214/

The server came back up and we punched it again, crashed again, the report is the same.

**Comment by kreezxil** [comment]
What's a milestone?

**Comment by frodare** [comment]
We are using github milestones track our releases, this is what we have for the next one: https://github.com/ToroCraft/ToroQuest/milestone/4?closed=1

You comment narrows it down a little more, so I am moving this back to our next release.  There must be another mod doing something the data attributes, ... or I am just using them wrong.  I wrapped that call in a try/catch in an attempt to stop the crash.  That might prevent the Toro's attack animation, but that is better than crashing!

**Comment by frodare** [comment]
The attempted fix is in this version: https://minecraft.curseforge.com/projects/toroquest/files/2369372

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/b0d2e760b3cde7ea65517955b2642440

This crashed our server - player had hurt a cow and a bull came at her.

**Comment by frodare** [comment]
@ProsperCraft please install the new version and see if this crash still happens.

**Comment by ProsperCraft** [comment]
Not fixed server still crashes when they get agro. - https://gist.github.com/ProsperCraft/1584396a417c723fb5ff6d3f42f23e9b

**Comment by frodare** [comment]
Well, that's a bummer.  I wish I could get it to crash on my computer, it's probably be trivial fix. I will take another stab at it.

**Comment by ProsperCraft** [comment]
Try with the One Elf Squared modpack from curse.  It might be a mod conflict.

**Comment by kradlyn** [comment]
I am seeing this crash as well when using the One Elf Squared mod pack.  When just loading Toro and forge though I cannot replicate the crash so I would hazard that it is another mod in the pack causing the issue.

**Comment by frodare** [comment]
It does seems like a mod conflict. Thanks everyone for all the input on this one.  I have just released a new build, 3.1, with another fix attempt: https://minecraft.curseforge.com/projects/toroquest/files/2379147
If that doesn't work I will need some help narrowing down which mod it is not playing nice with.

**Comment by kradlyn** [comment]
Build 3.1 did not fix the issue with the One Elf Squared pack.  I did find the mod that is causing the issue though.  It is the Epic Siege Mod which can be found here: https://minecraft.curseforge.com/projects/epic-siege-mod . Removing just this mod from the pack and you can fight a Toro all day long with no crashes.

**Comment by frodare** [comment]
And I really thought that was going to work, boo.  @kradlyn that is a great find!  I will download it and see if there is a way to make TQ compatible with it.

**Comment by kreezxil** [comment]
Thank you

-----Original Message-----

**Comment by GenDeathrow** [comment]
A fix for this is removing Toro from the ESM list. Thier is a config option in esm to remove certain entties as some may not like having AI replaced. Its normally up to pack devs to do this.

**Comment by kreezxil** [comment]
This wasn't obvious, thanks for sharing.

-----Original Message-----

**Comment by frodare** [comment]
I think this one is solved, thanks @GenDeathrow !

**Comment by frodare** [comment]
https://minecraft.curseforge.com/projects/toroquest?comment=37

**Comment by frodare** [comment]
OK, I finally got some free time to look into this problem again and I believe I have the problem!  I will try to get a new version up tonight.

**Comment by frodare** [comment]
Had more time than I thought this morning, new version has been uploaded.

**Comment by Hellcommander** [comment]
thanks though taking bit of a brake from minecraft


-----Original Message-----
